### ISSUE TITLE
Question about acknowledgement

### ISSUE THREAD

**Issue by JLChnToZ** [MineList/MinePing#1]
Hi, I am the original author of MCS2, and I have a question about the header of the script.

I have just noticed the difference between the script file in this repository and the original one from mine, the copyright header was disappeared in your version.

I'm glad to see my code is being shared and someone contribute it, but please do not remove the copyright notice. It is okay to add yours, of cause, as you make changes with it.

Thanks a lot! (And sorry for my bad English)

**Comment by ryush00** [comment]
Sorry. I missed them. :)

I have added the header.

Thank you for making wonderful codes!
