### ISSUE TITLE
Issue with pinging a server with ServerListPlus

### ISSUE THREAD

**Issue by Sir-Will** [MineList/MinePing#5]
hey,
so I added ServerListPlus to few servers and since then MinePing returns a empty motd.

https://dinnerbone.com/minecraft/tools/status/ does show the motd so I assume MinePing can't handle the formatting?

**Comment by ryush00** [comment]
I have found out newer protocol is use Chat type (http://wiki.vg/Chat) for motd. However MinePing weren't programed for Chat type.

I have a plan to work that, but currently, I have no time to do that.

If you have a few time, please share your time for MinePing. Thank you.

---

최신 프로토콜에서는 motd에서 Chat 타입을 사용합니다. 그러나 현재 MinePing은 Chat 타입에 대응하지 못합니다.

조만간 해당 기능을 개발할 계획이 있지만, 시간이 안됩니다.

만약 시간이 남는다면, MinePing을 위해 시간을 나눠주세요! 감사합니다!

**Comment by Sir-Will** [comment]
I already switched to a different nodejs minecraft pinger.

**Comment by ryush00** [comment]
Ok. I'll close this issue.
